BEGIN
DECLARE
TYPE ARRAY_OBJECT IS TABLE OF BIMONEDACONTROL%ROWTYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;
CURSOR CONTROL IS SELECT * FROM BIMONEDACONTROL WHERE OPENITEMREFERENCE_REDEF = 'N';
BEGIN
	OPEN CONTROL;
		 FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 1000;
         LOOP
                /* OPENITEMREFERENCE_REDEF */
				FOR I IN 1 .. BK_ROWS.COUNT LOOP
				   UPDATE OPENITEMREFERENCE_REDEF SET OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPR_POLICYNUMBER =  BK_ROWS(I).POLICYNUMBER;
                END LOOP;
                FORALL I IN 1 .. BK_ROWS.COUNT
                    UPDATE BIMONEDACONTROL SET OPENITEMREFERENCE_REDEF = 'Y' WHERE POLICYID =  BK_ROWS(I).POLICYID;
               
            COMMIT;
			EXIT WHEN CONTROL%NOTFOUND;
            END LOOP;
		COMMIT;
	CLOSE CONTROL;
END;              
DECLARE
TYPE ARRAY_OBJECT IS TABLE OF BIMONEDACONTROL%ROWTYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;

CURSOR CONTROL IS SELECT * FROM BIMONEDACONTROL WHERE STPO_POLICYASLOGICAL = 'N';
BEGIN
	OPEN CONTROL;
		 FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 1000;
         LOOP
				/* STPO_POLICYASLOGICAL */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                    UPDATE STPO_POLICYASLOGICAL SET PAL_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE PAL_POLICYNUMBER =  BK_ROWS(I).POLICYNUMBER;
                END LOOP;
                FORALL I IN 1 .. BK_ROWS.COUNT
                    UPDATE BIMONEDACONTROL SET STPO_POLICYASLOGICAL = 'Y' WHERE POLICYID =  BK_ROWS(I).POLICYID;
                
            COMMIT;
			EXIT WHEN CONTROL%NOTFOUND;
            END LOOP;
		COMMIT;
	CLOSE CONTROL;
END;  
DECLARE
TYPE ARRAY_OBJECT IS TABLE OF INTERSEGURO.OPENITEM.OPENITEMID%TYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;
CURSOR CONTROL IS SELECT OPENITEMID FROM OPENITEMREFERENCE WHERE OPR_POLICYNUMBER IN (SELECT POLICYNUMBER FROM BIMONEDACONTROL WHERE EXT_INTERFZSAMP = 'N');
BEGIN
	OPEN CONTROL;
		 FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 1000;
         LOOP
                 /* EXT_INTERFZSAMP */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                     UPDATE EXT_INTERFZSAMP SET NUMERO_POLIZA = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPENITEMID = BK_ROWS(I).OPENITEMID;
                END LOOP;
                FORALL I IN 1 .. BK_ROWS.COUNT
                    UPDATE BIMONEDACONTROL SET EXT_INTERFZSAMP = 'Y' WHERE POLICYID =  BK_ROWS(I).POLICYID;
            COMMIT;
			EXIT WHEN CONTROL%NOTFOUND;
            END LOOP;
		COMMIT;
	CLOSE CONTROL;
END;
DECLARE
TYPE ARRAY_OBJECT IS TABLE OF INTERSEGURO.OPENITEM.OPENITEMID%TYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;

CURSOR CONTROL IS  SELECT OPENITEMID FROM OPENITEMREFERENCE WHERE OPR_POLICYNUMBER IN (SELECT POLICYNUMBER FROM BIMONEDACONTROL WHERE EXT_TCIOPENITEMINFO = 'N');
BEGIN
	OPEN CONTROL;
		 FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 1000;
         LOOP
                 /* EXT_TCIOPENITEMINFO */
                  FOR I IN 1 .. BK_ROWS.COUNT LOOP
                UPDATE EXT_TCIOPENITEMINFO SET POLICY_NUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPENITEMID = BK_ROWS(I).OPENITEMID;
                END LOOP;
                FORALL I IN 1 .. BK_ROWS.COUNT
                    UPDATE BIMONEDACONTROL SET EXT_TCIOPENITEMINFO = 'Y' WHERE POLICYID =  BK_ROWS(I).POLICYID;
            COMMIT;
			EXIT WHEN CONTROL%NOTFOUND;
            END LOOP;
		COMMIT;
	CLOSE CONTROL;
END;
DECLARE
TYPE ARRAY_OBJECT IS TABLE OF BIMONEDACONTROL%ROWTYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;

CURSOR CONTROL IS SELECT * FROM BIMONEDACONTROL WHERE OPENITEMREFERENCE = 'N';
BEGIN
	OPEN CONTROL;
		 FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 1000;
         LOOP
                /* OPENITEMREFERENCE */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                UPDATE OPENITEMREFERENCE SET OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER;
                END LOOP;
                FORALL I IN 1 .. BK_ROWS.COUNT
                    UPDATE BIMONEDACONTROL SET OPENITEMREFERENCE = 'Y' WHERE POLICYID =  BK_ROWS(I).POLICYID;
            COMMIT;
			EXIT WHEN CONTROL%NOTFOUND;
            END LOOP;
		COMMIT;
	CLOSE CONTROL;
END; 
DECLARE
TYPE ARRAY_OBJECT IS TABLE OF BIMONEDACONTROL%ROWTYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;

CURSOR CONTROL IS SELECT * FROM BIMONEDACONTROL WHERE PROCESSED = 'N';
BEGIN
	OPEN CONTROL;
		 FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 1000;
         LOOP
                 /* PREPOLICY */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                    UPDATE PREPOLICY SET NUMEROPOLIZAINPUT = BK_ROWS(I).POLICYNUMBER || '-1' WHERE NUMEROPOLIZAINPUT = BK_ROWS(I).POLICYNUMBER;
                END LOOP; 
                FORALL I IN 1 .. BK_ROWS.COUNT
                    UPDATE BIMONEDACONTROL SET PROCESSED = 'Y' WHERE POLICYID =  BK_ROWS(I).POLICYID;
            COMMIT;
			EXIT WHEN CONTROL%NOTFOUND;
            END LOOP;
		COMMIT;
	CLOSE CONTROL;
END;          
END;