UPDATE INTERSEGURO.PREPRODUCT SET BIMONEDAINPUT='Si',BIMONEDAVALUE = '1.0' WHERE CODIGOPRODUCTOASINPUT = 'DESGRAVAMEN TARJETAS INDIVIDUAL';
COMMIT;
INSERT INTO INTERSEGURO.STST_SYSTEMPROPERTY (SYP_PROPERTY, SYP_VALUE, SYP_TYPE, SYP_MODULE, SYP_ISNULLABLE) VALUES ('enableDualCurrencySearch', 'Y', 7, 'PO', 1);
COMMIT;
ALTER TABLE INTERSEGURO.INT_DESG_PROCESS ADD SALDO_PROMEDIO VARCHAR2(50 BYTE);
COMMIT;
UPDATE INTERSEGURO.STPS_AGREEMENTSTATICDAT SET AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK' 
WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK Soles';
COMMIT;
UPDATE INTERSEGURO.STAG_AGREEMENTVERSION SET DESCRIPTION = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK - Soles/Dolares'
WHERE AST_ID = (SELECT AST_ID FROM INTERSEGURO.STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK');
COMMIT;
UPDATE INTERSEGURO.POLMATRIZPB SET MONEDAACUERDOINPUT='Nuevo Sol,US Dolar' WHERE PK IN (SELECT DCOID FROM INTERSEGURO.STAG_AGREEMENTVERSION WHERE AST_ID =
(SELECT AST_ID FROM INTERSEGURO.STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK'));
COMMIT;