UPDATE INTERSEGURO.PREPRODUCT SET BIMONEDAINPUT='Si',BIMONEDAVALUE = '1.0' WHERE CODIGOPRODUCTOASINPUT = 'DESGRAVAMEN TARJETAS INDIVIDUAL';
COMMIT;
INSERT INTO STST_SYSTEMPROPERTY (SYP_PROPERTY, SYP_VALUE, SYP_TYPE, SYP_MODULE, SYP_ISNULLABLE) VALUES ('enableDualCurrencySearch', 'Y', 7, 'PO', 1);
COMMIT;
ALTER TABLE INT_DESG_PROCESS ADD SALDO_PROMEDIO VARCHAR2(50 BYTE);
COMMIT;
UPDATE STPS_AGREEMENTSTATICDAT SET AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK' 
WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK Soles';
COMMIT;
UPDATE STAG_AGREEMENTVERSION SET DESCRIPTION = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK - Soles/Dolares'
where ast_id = (SELECT AST_ID FROM STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK');
COMMIT;
UPDATE POLMATRIZPB SET MONEDAACUERDOINPUT='Nuevo Sol,US Dolar' WHERE PK IN (SELECT dcoid FROM STAG_AGREEMENTVERSION WHERE AST_ID =
(SELECT AST_ID FROM STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK'));
COMMIT;