ALTER TABLE INTERSEGURO.INT_DESG_PROCESS ADD SEXO_ASEG VARCHAR2(50 BYTE);
ALTER TABLE INTERSEGURO.INT_DESG_PROCESS ADD TASA_CREDITO VARCHAR2(50 BYTE);
ALTER TABLE INTERSEGURO.INT_DESG_PROCESS ADD CUOTAS_PAG VARCHAR2(50 BYTE);
ALTER TABLE INTERSEGURO.INT_DESG_PROCESS ADD CUOTAS_PEND VARCHAR2(50 BYTE);
COMMIT;
