SELECT *
FROM
         AZTECA_V138.CLAIM CL
    JOIN AZTECA_V138.AGREGATEDPOLICY      AP ON CL.POLICYID = AP.AGREGATEDPOLICYID 
    JOIN AZTECA_V138.PREPOLICY            PPOL ON  PPOL.STATIC = AP.AGREGATEDPOLICYID 
    JOIN AZTECA_V138.PRODUCT              P ON AP.PRODUCTID = P.PRODUCTID
    JOIN AZTECA_V138.PREPRODUCT           PP ON P.PRO_DCOID = PP.PK
    JOIN AZTECA_V138.CLAIMRISKUNIT        CRU ON CL.CLAIMID = CRU.CLAIMID
    JOIN AZTECA_V138.CLAIMINSURANCEOBJECT CIO ON CRU.CLAIMRISKUNITID = CIO.CLAIMRISKUNITID
    JOIN AZTECA_V138.CLAIMNORMALRESERVE   CNR ON CIO.CLAIMINSURANCEOBJECTID = CNR.CLAIMINSURANCEOBJECTID
WHERE
    CNR.CLAIMNORMALRESERVEDID NOT IN (
        SELECT
            CLAIMNORMALRESERVEDID
        FROM
            AZTECA_V138.STCL_RESERVEDISEASE
    )
    AND PP.COMPANIAVALUE = '1.0';