SELECT 
CL.CLAIMNUMBER, 
CRU.CLAIMRISKUNITID,
CRU.OPERATIONPK,
CIO.CLAIMINSURANCEOBJECTID,
CIO.DESCRIPTION, 
CIO.DAMAGEDCOID,
CIO.DAMAGEDCOTEMPLATE,
CNR.CLAIMNORMALRESERVEDID,
CNR.DESCRIPTION,
CNR.RESERVELIMIT,
CNR.CNR_MAXPAYMENTAMOUNT
FROM AZTECA_V138.CLAIM  CL
JOIN AZTECA_V138.CLAIMRISKUNIT CRU ON CL.CLAIMID = CRU.CLAIMID
JOIN AZTECA_V138.CLAIMINSURANCEOBJECT CIO ON CRU.CLAIMRISKUNITID = CIO.CLAIMRISKUNITID
JOIN AZTECA_V138.CLAIMNORMALRESERVE CNR ON CIO.CLAIMINSURANCEOBJECTID = CNR.CLAIMINSURANCEOBJECTID
WHERE CL.CLAIMNUMBER = 'NVMX-2023-54';