select por.DATEPAYMENTORDER, por.COMMITMENTDATE, por.POR_ENDDATE, por.POR_STARTDATE, por.DONEBY,inv.COVI_INVOICE,CAL_STATUS from
(select  substr( cph.CAPH_RECORD,INSTR (cph.CAPH_RECORD,'|',3,20)+1,INSTR (cph.CAPH_RECORD,'|',3,21)-INSTR (cph.CAPH_RECORD,'|',3,20)-1) fac,clg.CAL_STATUS,
cph.CAPH_RECORD from INTERSEGURO.STPO_CLAIMASLHEADER hh 
inner join INTERSEGURO.STPO_CLAIMASLOGICAL clg on clg.CALH_PK = hh.CALH_PK
inner join INTERSEGURO.STPO_CLAIMASLPHYSICAL cph on cph.CAL_PK = clg.CAL_PK
where upper(hh.CALH_FILENAME) like 'FACTURA%') fac
inner join INTERSEGURO.STCL_COVERAGEINVOICE inv on inv.COVI_INVOICE = fac.fac
inner join INTERSEGURO.STCL_COVERAGEINVOICEPAYMENT cp on cp.COVI_INVOICE = inv.COVI_INVOICE
inner join INTERSEGURO.PAYMENTORDER por on por.PAYMENTORDERID = cp.PAYMENTORDERID
where por.DONEBY <> 'migration' and CAL_STATUS = 1
;