----------------------------------------Consulta 1--------------------------------------------
select  PK,STATIC,STATUS,ACCOUNTISMANUAL,REFERENCEISMANUAL,DATEISMANUAL, TYPEISMANUAL,ENTAMOUNTISMANUAL, SUMMARIZEDISMANUAL, ENTRYFILEID,ACCOUNTINPUT,ACCOUNTVALUE,REFERENCEINPUT, REFERENCEVALUE,DATEINPUT,DATEVALUE,TYPEINPUT,TYPEVALUE, ENTAMOUNTCARGOINPUT, ENTAMOUNTCARGOVALUE,ENTAMOUNTABONOINPUT,ENTAMOUNTABONOVALUE,ENTCODTIPOMOVINPUT,ENTCODTIPOMOVVALUE,
ENTDESCTIPOMOVINPUT, ENTDESCTIPOMOVVALUE,ENTFECHAGENERACIONINPUT,ENTFECHAGENERACIONVALUE,ENTNUMEROPOLIZAINPUT, ENTNUMEROPOLIZAVALUE, ENTPOLIZAPKINPUT,ENTPOLIZAPKVALUE,ENTTIPOCAMBIOINPUT,
ENTTIPOCAMBIOVALUE, ENTAMOUNTOPERACIONINPUT,ENTAMOUNTOPERACIONVALUE,ENTNOMBASEGURADORAINPUT, ENTNOMBASEGURADORAVALUE, ENTNUMEROSINIINPUT,ENTNUMEROSINIVALUE,ENTNUMOPERACIONINPUT,ENTNUMOPERACIONVALUE,
ENTNOMBREEVENTOINPUT, ENTNOMBREEVENTOVALUE,ENTMONEDAINPUT,ENTMONEDAVALUE,ENTRAMOCONTABLEINPUT, ENTRAMOCONTABLEVALUE, ENTIDTECEROINPUT,ENTIDTECEROVALUE,ENTGLINPUT,ENTGLVALUE,ENTCODIGOPLANINPUT,
ENTCODIGOPLANVALUE, ENTCODIGOPRODUCTOINPUT, ENTCODIGOPRODUCTOVALUE,ENTNUMEROMOVIMIENTOINPUT, ENTNUMEROMOVIMIENTOVALUE, IDSAPINPUT,IDSAPVALUE, DOCSAPINPUT, DOCSAPVALUE, FECDOCSAPINPUT, FECDOCSAPVALUE,
STSSAPINPUT, STSSAPVALUE, ENTNOMPROVEEDORINPUT, ENTNOMPROVEEDORVALUE, ENTCANALINPUT,ENTCANALVALUE
 from AZTECA_V138.entry
where to_date(dateinput,'DD-MM-YYYY')=TO_DATE('27-12-2022','DD-MM-YYYY')
AND STATUS='0'
AND ENTNOMBASEGURADORAINPUT='SEGUROS AZTECA DAÑOS, S.A. de C.V.'
and entdesctipomovinput='EMISIÓN';

----------------------------------------Consulta 2--------------------------------------------
select PK,STATIC,STATUS,ACCOUNTISMANUAL,REFERENCEISMANUAL,DATEISMANUAL,TYPEISMANUAL, ENTAMOUNTISMANUAL, SUMMARIZEDISMANUAL, ENTRYFILEID, ACCOUNTINPUT,ACCOUNTVALUE,REFERENCEINPUT,
REFERENCEVALUE, DATEINPUT, DATEVALUE ,TYPEINPUT, TYPEVALUE,ENTAMOUNTCARGOINPUT, ENTAMOUNTCARGOVALUE, ENTAMOUNTABONOINPUT, ENTAMOUNTABONOVALUE, ENTCODTIPOMOVINPUT, ENTCODTIPOMOVVALUE,
ENTDESCTIPOMOVINPUT, ENTDESCTIPOMOVVALUE, ENTFECHAGENERACIONINPUT, ENTFECHAGENERACIONVALUE, ENTNUMEROPOLIZAINPUT, ENTNUMEROPOLIZAVALUE, ENTPOLIZAPKINPUT,ENTPOLIZAPKVALUE,ENTTIPOCAMBIOINPUT,
ENTTIPOCAMBIOVALUE, ENTAMOUNTOPERACIONINPUT, ENTAMOUNTOPERACIONVALUE, ENTNOMBASEGURADORAINPUT, ENTNOMBASEGURADORAVALUE, ENTNUMEROSINIINPUT, ENTNUMEROSINIVALUE,ENTNUMOPERACIONINPUT, ENTNUMOPERACIONVALUE,
ENTNOMBREEVENTOINPUT, ENTNOMBREEVENTOVALUE, ENTMONEDAINPUT, ENTMONEDAVALUE, ENTRAMOCONTABLEINPUT, ENTRAMOCONTABLEVALUE, ENTIDTECEROINPUT, ENTIDTECEROVALUE, ENTGLINPUT,ENTGLVALUE,ENTCODIGOPLANINPUT,
ENTCODIGOPLANVALUE, ENTCODIGOPRODUCTOINPUT, ENTCODIGOPRODUCTOVALUE, ENTNUMEROMOVIMIENTOINPUT, ENTNUMEROMOVIMIENTOVALUE, IDSAPINPUT, IDSAPVALUE, DOCSAPINPUT, DOCSAPVALUE, FECDOCSAPINPUT,FECDOCSAPVALUE,
STSSAPINPUT, STSSAPVALUE, ENTNOMPROVEEDORINPUT, ENTNOMPROVEEDORVALUE,ENTCANALINPUT,ENTCANALVALUE
 from AZTECA_V138.entry
where to_date(dateinput,'DD-MM-YYYY')=TO_DATE('27-12-2022','DD-MM-YYYY')
AND STATUS='0'
AND ENTNOMBASEGURADORAINPUT='SEGUROS AZTECA DAÑOS, S.A. de C.V.'
and entdesctipomovinput='CANCELACIÓN';
