-------------------- SINIESTRO FUERA DE VIGENCIA - RAFAEL --------------------

SELECT CLAIMID,CLAIMDATE,POLICYID,POLICYDATE,CLAIMNUMBER,OPERATIONPK,USC_LOGIN FROM AZTECA_V138.CLAIM WHERE CLAIMNUMBER = 'VTC1-2023-42';

-------------------- VERSION DE BD AZTECA - DBA CONSIS --------------------

SELECT BANNER,BANNER_FULL,BANNER_LEGACY,CON_ID FROM  V$VERSION;

-------------------- SINIESTROS QUE VIOLARON LOS CANDADOS --------------------
SELECT PRO.DESCRIPTION,PREPO.NUMEROPOLIZAINPUT, CLA.CLAIMNUMBER, CLA.CLAIMDATE,CLA.POLICYDATE,PREPO.FECHAEMISIONINPUT,CLA.OPERATIONPK,PO.INITIALDATE,PO.FINISHDATE 
FROM AZTECA_V138.CLAIM CLA
JOIN AZTECA_V138.POLICYDCO PO ON CLA.OPERATIONPK = PO.OPERATIONPK
JOIN AZTECA_V138.AGREGATEDPOLICY AG ON AG.AGREGATEDPOLICYID = PO.AGREGATEDOBJECTID
JOIN AZTECA_V138.PRODUCT PRO ON PRO.PRODUCTID = AG.PRODUCTID
INNER JOIN AZTECA_V138.PREPOLICY  PREPO ON PREPO.PK = PO.DCOID
WHERE (CLA.CLAIMDATE < TO_DATE(PREPO.FECHAEMISIONINPUT,'dd-mm-yy') OR CLA.POLICYDATE < TO_DATE(PREPO.FECHAEMISIONINPUT,'dd-mm-yy'))
AND USC_LOGIN <> 'migracion';

------------------ SINIESTROS CON ORDENES DE PAGO SIN VISUALIZAR EN NOTIFICACION --------------------------
SELECT CL.CLAIMNUMBER, CL.CLAIMID,PO.PAYMENTORDERID,PO.DATEPAYMENTORDER,PO.COMMITMENTDATE,PO.FKRESERVE,PO.RESERVETYPE,PO.THIRDPARTYID,
PO.ROL_ID,PO.CPY_ID,PO.BENEFICIARY,PO.REASON,PO.STATE,PO.TYPE,PO.AMOUNT,PO.DONEBY,PO.PARTICIPATIONPERCENTAGE,PO.DEDUCTIBLEPERCENTAGE,
PO.DEDUCTIBLEREFERENCE, PO.ISDEDUCTIBLEAPPLIED,PO.DEDUCTIBLEAMOUNT,PO.ISPENALTYAPPLIED,PO.PENALTYPERCENTAGE,PO.ISREFUNDAPPLIED,
PO.REFUNDPERCENTAGE,PO.ISTOTALPAYMENT,PO.DISTRIBUTIONAMOUNT,PO.POR_OPERATIONDATE,PO.POR_STARTDATE,
PO.COVERAGEDESC,PO.POR_ONHOLD,PO.CRBF_ID,PO.POR_ENDDATE,PO.POR_NUMBER,PO.POR_BENEFICIARY_ID,PO.POR_BRANCH,
PO.POR_DEFAULTDEDUCTIBLE,PO.POR_FRANCHISEAMOUNT,PO.POR_ADDITIONALINFORMATION,PO.POR_DEDUCTIBLETYPE,PO.POR_FINAL,PO.POR_ITEMRESERVE,
PO.POR_GENERATEPREMIUMDEPOSIT,PO.POR_PARTAMOUNT,PO.POR_AUTORIZED
FROM AZTECA_V138.PAYMENTORDER PO
JOIN AZTECA_V138.CLAIMNORMALRESERVE CNR ON CNR.CLAIMNORMALRESERVEDID = PO.FKRESERVE
JOIN AZTECA_V138.CLAIMINSURANCEOBJECT CIO ON CIO.AGREGATEDINSURANCEOBJECTID = CNR.CLAIMINSURANCEOBJECTID
JOIN AZTECA_V138.CLAIMRISKUNIT CRU ON CRU.CLAIMRISKUNITID = CIO.CLAIMRISKUNITID
JOIN AZTECA_V138.CLAIM CL ON CL.CLAIMID = CRU.CLAIMID
LEFT JOIN AZTECA_V138.CLAIMPAYMENT CP ON CP.CLAIMID = CL.CLAIMID
WHERE CL.USC_LOGIN<>'migracion' AND CPY_ID IS NULL;

--------------------- SINIESTROS CON PAGOS PENDIENTES POR APROBAR -------------------------------------
SELECT CP.CLAIMPAYMENTID,CP.CLAIMID,CP.CLAIMPAYMENTDATE,CP.COVERAGEDESCRIPTION,CP.RESERVETYPE,CP.THIRDPARTYID,CP.BENEFICIARY,
CP.STATE,CP.AMOUNT,CP.PAIDAMOUNT,CP.DONEBY,CP.RESERVECURRENCYID,CP.PAIDCURRENCYID,CP.EXCHANGERATE,CP.DEDUCTIBLEPERCENTAGE,
CP.DEDUCTIBLEREFERENCE,CP.ISDEDUCTIBLEAPPLIED,CP.DEDUCTIBLEAMOUNT,CP.ISPENALTYAPPLIED,CP.PENALTYPERCENTAGE,
CP.ISREFUNDAPPLIED,CP.REFUNDPERCENTAGE,CP.ISTOTALPAYMENT,CP.CPY_FRANCHISEAMOUNT
FROM AZTECA_V138.CLAIMPAYMENT CP
JOIN AZTECA_V138.CLAIM CL ON CL.CLAIMID = CP.CLAIMID
WHERE CL.CLAIMID IN (SELECT CL.CLAIMID
FROM AZTECA_V138.PAYMENTORDER PO
JOIN AZTECA_V138.CLAIMNORMALRESERVE CNR ON CNR.CLAIMNORMALRESERVEDID = PO.FKRESERVE
JOIN AZTECA_V138.CLAIMINSURANCEOBJECT CIO ON CIO.AGREGATEDINSURANCEOBJECTID = CNR.CLAIMINSURANCEOBJECTID
JOIN AZTECA_V138.CLAIMRISKUNIT CRU ON CRU.CLAIMRISKUNITID = CIO.CLAIMRISKUNITID
JOIN AZTECA_V138.CLAIM CL ON CL.CLAIMID = CRU.CLAIMID
WHERE CL.USC_LOGIN<>'migracion' AND PO.CPY_ID IS NULL);
