SELECT COUNT(OI.OPENITEMID) FROM OPENITEM OI
	JOIN OPENITEMREFERENCE OIR ON OIR.OPENITEMID = OI.OPENITEMID
	WHERE OI.OPM_MASTEROPENITEMID IS NULL AND OI.DTY_ID <> 7612 AND OI.STATUS NOT IN ('deleted') AND OIR.OPR_PRODUCTPK = 73585;