SELECT COUNT(DISTINCT PRE.NUMEROPOLIZAINPUT)
			FROM INTERSEGURO.AGREGATEDPOLICY AG
	JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	JOIN INTERSEGURO.PREPOLICY PRE ON PRE.STATIC = AG.AGREGATEDPOLICYID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') 
	AND TO_DATE(FECHAEMISIONINPUT,'YYYY-MM-DD') > TO_DATE('2020-12-31','YYYY-MM-DD');