SELECT DISTINCT PRE.NUMEROPOLIZAINPUT
			FROM INTERSEGURO.AGREGATEDPOLICY AG
	JOIN PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	JOIN PREPOLICY PRE ON PRE.STATIC = AG.AGREGATEDPOLICYID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') 
	