WITH TEMPORAL AS (SELECT AP.AGREGATEDPOLICYID,P.DESCRIPTION
                  FROM INTERSEGURO.PRODUCT P
                  INNER JOIN INTERSEGURO.AGREGATEDPOLICY AP ON P.PRODUCTID = AP.PRODUCTID
                  INNER JOIN INTERSEGURO.PRODUCTPROPERTY PP ON PP.PRO_ID = P.PRODUCTID AND PP.PRP_TYPE = 2 )

SELECT X.* FROM (SELECT 
CO.ID AS OPERACION,
TRUNC(CO.INITIAL_DATE,'DD') AS FECHA_DESDE,
TRUNC(CO.ENDING_DATE,'DD') AS FECHA_HASTA,
(SELECT NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY WHERE STATIC = CO.ITEM AND ROWNUM = 1) AS POLIZA,
CO.USER_NAME AS USUARIO,
E2.DESCRIPTION AS EVENTO,
TEMP.DESCRIPTION,
(SELECT COUNT(OPENITEMID) FROM INTERSEGURO.OPENITEM OI WHERE OI.OPERATIONPK = P.OPERATIONPK) AS TOTAL_IO
FROM INTERSEGURO.CONTEXTOPERATION CO
INNER JOIN INTERSEGURO.POLICYDCO P on CO.ID = P.OPERATIONPK AND CO.STATUS = 2
INNER JOIN INTERSEGURO.EVENTDCO E on P.IDDCOEVENT = E.IDDCOEVENT
INNER JOIN INTERSEGURO.EVENTTYPE E2 ON E2.EVENTTYPEID = E.EVENTTYPEID
INNER JOIN TEMPORAL TEMP ON TEMP.AGREGATEDPOLICYID = P.AGREGATEDOBJECTID 
WHERE E2.DESCRIPTION in ('Emitir','AprobarEndoso','Renovar','GenerarPrima'))X
WHERE X.TOTAL_IO = 0 and X.USUARIO NOT IN ('migration');