SELECT E2.DESCRIPTION,
       (SELECT COUNT(OI.OPENITEMID) FROM INTERSEGURO.OPENITEM OI WHERE OI.OPERATIONPK = CO.ID) AS TOTAL_OI
    ,PP.FECHAPROXIMAGENPRIMAINPUT, PP.FECHAPROXIMAGENPRIMAVALUE
    ,CO.*
FROM INTERSEGURO.CONTEXTOPERATION CO
       INNER JOIN INTERSEGURO.POLICYDCO P on CO.ID = P.OPERATIONPK
       INNER JOIN INTERSEGURO.PREPOLICY PP ON PP.PK = P.DCOID
       INNER JOIN INTERSEGURO.EVENTDCO E on E.IDDCOEVENT = P.IDDCOEVENT
       INNER JOIN INTERSEGURO.EVENTDCO E on E.OPERATIONPK = P.OPERATIONPK
       INNER JOIN INTERSEGURO.EVENTTYPE E2 on E.EVENTTYPEID = E2.EVENTTYPEID
WHERE CO.ITEM = 80073669 
  AND CO.STATUS IN (2,7)
ORDER BY CO.AUDITDATE DESC;
