DROP USER   AZTECA_V138      CASCADE;
DROP USER   AZTECAGU_V138      CASCADE;
DROP TABLESPACE "TSDAT_AZTECA_V138" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "TSDAT_AZTECA_V13816" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "TSNDX_AZTECA_V138" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "TSNDX_AZTECA_V13816" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "TSNDX_AZTECAGU_V138" INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE "TSDAT_AZTECAGU_V138" INCLUDING CONTENTS AND DATAFILES;


CREATE BIGFILE TABLESPACE TSDAT_AZTECA_V138 DATAFILE 'C:\OracleDB\oradata\ORCL19C\acsele\TSDAT_AZTECA_V138.dbf' SIZE 20G AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE TSDAT_AZTECA_V13816 DATAFILE 'C:\OracleDB\oradata\ORCL19C\acsele\TSDAT_AZTECA_V13816.dbf' SIZE 10G AUTOEXTEND ON NEXT 16M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE TSNDX_AZTECA_V138 DATAFILE 'C:\OracleDB\oradata\ORCL19C\acsele\TSNDX_AZTECA_V138.dbf' SIZE 20G AUTOEXTEND ON NEXT 256M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE TSNDX_AZTECA_V13816 DATAFILE 'C:\OracleDB\oradata\ORCL19C\acsele\TSNDX_AZTECA_V13816.dbf' SIZE 5G AUTOEXTEND ON NEXT 16M MAXSIZE UNLIMITED
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 16K
SEGMENT SPACE MANAGEMENT AUTO;

CREATE BIGFILE TABLESPACE TSNDX_AZTECAGU_V138 DATAFILE 'C:\OracleDB\oradata\ORCL19C\acsele\TSNDX_AZTECAGU_V138.dbf' SIZE 200M AUTOEXTEND ON NEXT 16M MAXSIZE 5G
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE BIGFILE TABLESPACE TSDAT_AZTECAGU_V138 DATAFILE 'C:\OracleDB\oradata\ORCL19C\acsele\TSDAT_AZTECAGU_V138.dbf' SIZE 200M AUTOEXTEND ON NEXT 16M MAXSIZE 5G
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE USER AZTECA_V138
  IDENTIFIED BY AZTECA_V138
  DEFAULT TABLESPACE TSDAT_AZTECA_V138
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
CREATE USER AZTECAGU_V138
  IDENTIFIED BY AZTECAGU_V138
  DEFAULT TABLESPACE TSDAT_AZTECAGU_V138
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  
grant connect,resource to AZTECAGU_V138,AZTECA_V138;
grant unlimited tablespace to AZTECAGU_V138,AZTECA_V138;

GRANT CREATE ANY VIEW TO AZTECA_V138 WITH ADMIN OPTION;
GRANT CREATE VIEW TO AZTECA_V138 WITH ADMIN OPTION;
GRANT CREATE ANY MATERIALIZED VIEW TO AZTECA_V138 WITH ADMIN OPTION;
GRANT CREATE MATERIALIZED VIEW TO AZTECA_V138 WITH ADMIN OPTION;



-- importar

impdp system/oracle01 dumpfile=BKP_EXPDP_ACSELE_2021_06_17_%u.dmp schemas=AZTECA_V138, AZTECAGU_V138 logfile=AZTECA_V138_expdp16072021.log exclude=grant parallel=6
