DECLARE
TYPE OPENITEMS_IDS IS TABLE OF OPENITEM.OPENITEMID%TYPE
              INDEX BY PLS_INTEGER; 
    OILIST OPENITEMS_IDS;
  
    CURSOR C IS
	
	SELECT OI.OPENITEMID FROM OPENITEM OI
	JOIN OPENITEMREFERENCE OIR ON OIR.OPENITEMID = OI.OPENITEMID
	WHERE OI.OPM_MASTEROPENITEMID IS NULL AND OI.DTY_ID <> 7612 AND OI.STATUS NOT IN ('deleted') AND OIR.OPR_PRODUCTPK = 73585;
		
BEGIN
    OPEN C;
    LOOP
        FETCH C BULK COLLECT INTO OILIST LIMIT 10000;
        BEGIN
            FORALL I IN 1 .. OILIST.LAST SAVE EXCEPTIONS
                UPDATE OPENITEM SET OPM_MASTEROPENITEMID = 0 WHERE OPENITEMID = OILIST(I) ;
        EXCEPTION
            WHEN OTHERS
                THEN
                    DBMS_OUTPUT.PUT_LINE (SQLERRM);
        END;
        EXIT WHEN C%NOTFOUND;
        COMMIT;
    END LOOP;
    CLOSE C;
EXCEPTION
    WHEN OTHERS
        THEN
            DBMS_OUTPUT.PUT_LINE (SQLERRM);
END;