DECLARE
TYPE ARRAY_OBJECT IS TABLE OF BIMONEDACONTROL%ROWTYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;
REC_COUNT  NUMBER := 0;
CURSOR CONTROL IS SELECT * FROM BIMONEDACONTROL WHERE PROCESSED = 'N';
BEGIN 
BEGIN
	OPEN CONTROL;
		LOOP FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 1;
			BEGIN
				FOR I IN 1 .. BK_ROWS.LAST 
				   UPDATE OPENITEMREFERENCE_REDEF SET OPR_POLICYNUMBER = BI.POLICYNUMBER || '-1' WHERE OPR_POLICYNUMBER = BI.POLICYNUMBER;
				   
				FOR I IN 1 .. BK_ROWS.LAST
				UPDATE STPO_POLICYASLOGICAL SET PAL_POLICYNUMBER = CURR_POL WHERE PAL_POLICYNUMBER = BI.POLICYNUMBER;
            FOR I IN 1 .. BK_ROWS.LAST
                UPDATE OPENITEMREFERENCE SET OPR_POLICYNUMBER = CURR_POL WHERE OPR_POLICYNUMBER = BI.POLICYNUMBER;
            FOR I IN 1 .. BK_ROWS.LAST
                UPDATE EXT_INTERFZSAMP SET NUMERO_POLIZA = CURR_POL WHERE NUMERO_POLIZA = BI.POLICYNUMBER;
            FOR I IN 1 .. BK_ROWS.LAST
                UPDATE EXT_TCIOPENITEMINFO SET POLICY_NUMBER = CURR_POL WHERE POLICY_NUMBER = BI.POLICYNUMBER;
            FOR I IN 1 .. BK_ROWS.LAST
                UPDATE PREPOLICY SET NUMEROPOLIZAINPUT = CURR_POL WHERE NUMEROPOLIZAINPUT = BI.POLICYNUMBER;
            FOR I IN 1 .. BK_ROWS.LAST
                UPDATE BIMONEDACONTROL SET PROCESSED = 'Y' WHERE POLICYID = BI.POLICYNUMBER;
			END;
			EXIT WHEN CONTROL%NOTFOUND;
			COMMIT;
		IF MOD (REC_COUNT, 100) = 0
			THEN
				REC_COUNT:=0;
				COMMIT;
		END IF;
		END LOOP;
		COMMIT;
	CLOSE CONTROL;
	END;
END;


                