CREATE TABLE BIMONEDACONTROL
(
  POLICYNUMBER  VARCHAR2(18),  
  CONSTRAINT BIPOLICYNUMBER UNIQUE (POLICYNUMBER)
);
COMMIT;
CREATE INDEX BIMONEDA_IDX
    ON BIMONEDACONTROL (POLICYNUMBER);
COMMIT;
DECLARE
TYPE ARRAY_OBJECT IS TABLE OF BIMONEDACONTROL%ROWTYPE INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;
CURSOR CONTROL IS SELECT DISTINCT PRE.NUMEROPOLIZAINPUT POLICYNUMBER
			FROM AGREGATEDPOLICY AG
	JOIN PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	JOIN PREPOLICY PRE ON PRE.STATIC = AG.AGREGATEDPOLICYID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') 
	AND to_date(FECHAEMISIONINPUT,'YYYY-MM-DD') > to_date('2020-12-31','YYYY-MM-DD')
	AND NOT EXISTS (SELECT 1 FROM BIMONEDACONTROL WHERE POLICYNUMBER = PRE.NUMEROPOLIZAINPUT);
BEGIN
	OPEN CONTROL;
    LOOP
		 FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 100;
         BEGIN
                /* OPENITEMREFERENCE_REDEF */
				FOR I IN 1 .. BK_ROWS.COUNT LOOP
				   UPDATE OPENITEMREFERENCE_REDEF SET OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPR_POLICYNUMBER =  BK_ROWS(I).POLICYNUMBER;
                END LOOP;
        
				/* STPO_POLICYASLOGICAL */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                    UPDATE STPO_POLICYASLOGICAL SET PAL_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE PAL_POLICYNUMBER =  BK_ROWS(I).POLICYNUMBER;
                END LOOP;
         
				 /* EXT_TCIOPENITEMINFO */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                    FOR X IN (SELECT OPENITEMID FROM OPENITEMREFERENCE WHERE OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER) LOOP
                        UPDATE EXT_TCIOPENITEMINFO SET POLICY_NUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPENITEMID = X.OPENITEMID;
                    END LOOP;
				END LOOP;
       
				 /* EXT_INTERFZSAMP */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                    FOR X IN (SELECT OPENITEMID FROM OPENITEMREFERENCE WHERE OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER) LOOP
                        UPDATE EXT_INTERFZSAMP SET NUMERO_POLIZA = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPENITEMID = X.OPENITEMID;
                    END LOOP;
                END LOOP;
  
				/* OPENITEMREFERENCE */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                    UPDATE OPENITEMREFERENCE SET OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER || '-1' WHERE OPR_POLICYNUMBER = BK_ROWS(I).POLICYNUMBER;
                END LOOP;
        
				  /* PREPOLICY */
                FOR I IN 1 .. BK_ROWS.COUNT LOOP
                    UPDATE PREPOLICY SET NUMEROPOLIZAINPUT = BK_ROWS(I).POLICYNUMBER || '-1' WHERE NUMEROPOLIZAINPUT = BK_ROWS(I).POLICYNUMBER;
                END LOOP;
         
                 FORALL I IN 1 .. BK_ROWS.LAST
				  INSERT INTO BIMONEDACONTROL VALUES BK_ROWS(I);
        END;
        COMMIT;
		EXIT WHEN CONTROL%NOTFOUND;
    END LOOP;
	CLOSE CONTROL;
END;   		