SELECT DISTINCT VS.SQL_TEXT, VS.SHARABLE_MEM,
VS.PERSISTENT_MEM, VS.RUNTIME_MEM, VS.SORTS,
VS.EXECUTIONS, VS.PARSE_CALLS, VS.MODULE,
VS.BUFFER_GETS, VS.DISK_READS, VS.VERSION_COUNT,
VS.USERS_OPENING, VS.LOADS,
TO_CHAR(TO_DATE(VS.FIRST_LOAD_TIME,
'YYYY-MM-DD/HH24:MI:SS'),'MM/DD HH24:MI:SS') FIRST_LOAD_TIME,
RAWTOHEX(VS.ADDRESS) ADDRESS, VS.HASH_VALUE HASH_VALUE ,
ROWS_PROCESSED , VS.COMMAND_TYPE, VS.PARSING_USER_ID ,
OPTIMIZER_MODE , AU.USERNAME PARSEUSER
FROM V$SQLAREA VS , ALL_USERS AU
WHERE (PARSING_USER_ID != 0) AND
(AU.USER_ID(+)=VS.PARSING_USER_ID)
AND (EXECUTIONS >= 1) ORDER BY BUFFER_GETS/EXECUTIONS DESC