DECLARE
TYPE ARRAY_OBJECT IS TABLE OF VARCHAR(80) INDEX BY BINARY_INTEGER;
BK_ROWS   ARRAY_OBJECT;
CURSOR CONTROL IS SELECT DISTINCT PRE.NUMEROPOLIZAINPUT
			FROM INTERSEGURO.AGREGATEDPOLICY AG
	JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	JOIN INTERSEGURO.PREPOLICY PRE ON PRE.STATIC = AG.AGREGATEDPOLICYID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual');
BEGIN
	OPEN CONTROL;
    LOOP
		FETCH CONTROL BULK COLLECT INTO BK_ROWS LIMIT 10000;
        BEGIN
            /* PREPOLICY */
			FOR I IN 1 .. BK_ROWS.COUNT LOOP
				UPDATE INTERSEGURO.PREPOLICY SET NUMEROPOLIZAINPUT = BK_ROWS(I) || '-1' WHERE NUMEROPOLIZAINPUT = BK_ROWS(I);
			END LOOP;
        END;
        COMMIT;
		EXIT WHEN CONTROL%NOTFOUND;
    END LOOP;
	CLOSE CONTROL;
END;   		
