/*TOTAL OPENITEMREFERENCE_REDEF*/
DECLARE
COUNTER NUMBER:=0;
BEGIN
	SELECT COUNT(1) INTO COUNTER FROM INTERSEGURO.OPENITEMREFERENCE_REDEF EXT
	WHERE OPR_POLICYNUMBER IN (SELECT PRE.NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY PRE
	JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
	JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual')  AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1);
	DBMS_OUTPUT.PUT_LINE('TOTAL OPENITEMREFERENCE_REDEF: '||COUNTER);
END

/*TOTAL STPO_POLICYASLOGICAL*/
DECLARE
COUNTER NUMBER:=0;
BEGIN
	SELECT COUNT(1) INTO COUNTER FROM INTERSEGURO.STPO_POLICYASLOGICAL EXT
	WHERE PAL_POLICYNUMBER IN (SELECT PRE.NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY PRE
	JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
	JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual')  AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1);
	dbms_output.put_line('TOTAL STPO_POLICYASLOGICAL: '||counter);
END

/*TOTAL EXT_TCIOPENITEMINFO*/
DECLARE
COUNTER NUMBER:=0;
BEGIN
	SELECT COUNT(1) INTO COUNTER FROM INTERSEGURO.EXT_TCIOPENITEMINFO EXT
	WHERE OPENITEMID IN (SELECT OPENITEMID FROM INTERSEGURO.OPENITEMREFERENCE WHERE OPR_POLICYNUMBER IN (SELECT PRE.NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY PRE
	JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
	JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual')  AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1)); 
	dbms_output.put_line('TOTAL EXT_TCIOPENITEMINFO: '||counter);
END;

/*TOTAL EXT_INTERFZSAMP*/
DECLARE
COUNTER NUMBER:=0;
BEGIN            
    SELECT COUNT(1) INTO COUNTER FROM INTERSEGURO.EXT_INTERFZSAMP EXT
    WHERE OPENITEMID IN (SELECT OPENITEMID FROM INTERSEGURO.OPENITEMREFERENCE WHERE OPR_POLICYNUMBER IN (SELECT PRE.NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY PRE
    JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
    JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
    WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1));
    dbms_output.put_line('TOTAL EXT_INTERFZSAMP: '||counter);
END;

/*TOTAL EXT_INTERFZSAMP*/
DECLARE
COUNTER NUMBER:=0;
BEGIN  			
	SELECT COUNT(1) INTO COUNTER FROM INTERSEGURO.OPENITEMREFERENCE EXT
	WHERE OPR_POLICYNUMBER IN (SELECT PRE.NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY PRE
    JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
    JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
    WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1);
    dbms_output.put_line('TOTAL OPENITEMREFERENCE: '||counter);
END;	
 
/*TOTAL POLIZA*/
DECLARE
COUNTER NUMBER:=0;
BEGIN
	SELECT COUNT(1) INTO COUNTER FROM INTERSEGURO.POLIZA EXT
	WHERE NUMEROPOLIZA IN (SELECT PRE.NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY PRE
    JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
    JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
    WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1);
    dbms_output.put_line('TOTAL INTERSEGURO.POLIZA: '||counter);
END;                
				
/*TOTAL INTERSEGUROR.POLIZA*/
DECLARE
COUNTER NUMBER:=0;
BEGIN
	SELECT COUNT(1) INTO COUNTER FROM INTERSEGUROR.POLIZA EXT
	WHERE NUMEROPOLIZA IN (SELECT PRE.NUMEROPOLIZAINPUT FROM INTERSEGURO.PREPOLICY PRE
	JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
	JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1);
	dbms_output.put_line('TOTAL INTERSEGUROR.POLIZA: '||counter);
END;