DECLARE
COUNTER NUMBER:=0;
BEGIN
SELECT COUNT(DISTINCT (PRE.NUMEROPOLIZAINPUT)) INTO COUNTER FROM INTERSEGURO.PREPOLICY PRE
        JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
        JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
        WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1;
		DBMS_OUTPUT.PUT_LINE('TOTAL PÓLIZAS: '||COUNTER);
COUNTER:=0;
SELECT COUNT(PRE.NUMEROPOLIZAINPUT) INTO COUNTER FROM INTERSEGURO.PREPOLICY PRE
        JOIN INTERSEGURO.AGREGATEDPOLICY AG ON PRE.STATIC = AG.AGREGATEDPOLICYID
        JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
        WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual') AND LENGTH(REGEXP_REPLACE(PRE.NUMEROPOLIZAINPUT,'[^-]'))<=1;
DBMS_OUTPUT.PUT_LINE('TOTAL MOVIMIENTOS POR PÓLIZA: '||COUNTER);
END;
