UPDATE INTERSEGURO.PREPRODUCT SET BIMONEDAINPUT='No',BIMONEDAVALUE = '0.0' WHERE CODIGOPRODUCTOASINPUT = 'DESGRAVAMEN TARJETAS INDIVIDUAL';
COMMIT;
DELETE INTERSEGURO.STST_SYSTEMPROPERTY WHERE STST_SYSTEMPROPERTY = 'enableDualCurrencySearch';
COMMIT;
UPDATE INTERSEGURO.STPS_AGREEMENTSTATICDAT SET AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK Soles' 
WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK';
COMMIT;
UPDATE INTERSEGURO.STAG_AGREEMENTVERSION SET DESCRIPTION = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK Soles'
WHERE AST_ID = (SELECT AST_ID FROM INTERSEGURO.STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK Soles');
COMMIT;
UPDATE INTERSEGURO.POLMATRIZPB SET MONEDAACUERDOINPUT='Nuevo Sol' WHERE PK IN (SELECT DCOID FROM INTERSEGURO.STAG_AGREEMENTVERSION WHERE AST_ID =
(SELECT AST_ID FROM INTERSEGURO.STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK Soles'));
COMMIT;