SELECT P.DESCRIPTION, LE.SLE_EVENTNAME, LE.SLE_DOCNAME, LT.LTP_LETTERTEMPLATEPATH, LP.*
FROM INTERSEGURO.STRP_SYSTEMDOCUMENTS SD
       INNER JOIN INTERSEGURO.STRP_LANGUAGETEMPLATE LT ON LT.SLT_ID = SDOC_ID
      INNER JOIN INTERSEGURO.STRP_LETTERPARAMETER LP ON LP.SLT_ID = SDOC_ID -- PARAMETROS DEL DOCUMENTO
       INNER JOIN INTERSEGURO.STRP_LETTEREVENT LE ON LE.SDOC_ID = SD.SDOC_ID
       INNER JOIN INTERSEGURO.PRODUCT P ON P.PRODUCTID = LE.PRO_ID
WHERE /*LT.LTP_LETTERTEMPLATEPATH LIKE '%CP%'
AND */LP.LTP_NAME = 'PLimiteEdadAsegurable'
AND P.DESCRIPTION = 'DotalDobleCapital';