/* SI EXISTE ELIMINAR LA TABLA */
DROP TABLE OPER_NOCOVERAGE;

/* CREAR TABLA TEMPORAL PARA OBTENER POLIZAS Y OPERACIONES */
CREATE TABLE OPER_NOCOVERAGE AS SELECT CT.ID AS OPERACION,COALESCE(PP.NUMEROPOLIZAINPUT,NUMEROCOTIZACIONINPUT) AS POLIZA,CT.TIME_STAMP FROM INTERSEGURO.CONTEXTOPERATION CT
  INNER JOIN INTERSEGURO.POLICYDCO PD ON PD.OPERATIONPK=CT.ID AND CT.STATUS=2
  INNER JOIN INTERSEGURO.PREPOLICY PP ON PD.DCOID=PP.PK
  LEFT JOIN INTERSEGURO.COVERAGEDCO C ON  C.OPERATIONPK=PD.OPERATIONPK
WHERE C.AGREGATEDOBJECTID IS NULL;

/* OBTIENE EL EVENTO Y EL PRODUCTO ASOCIADO */
SELECT TEMP.*,PRO.DESCRIPTION AS PRODUCTO,E2.DESCRIPTION AS EVENTO FROM OPER_NOCOVERAGE TEMP
INNER JOIN INTERSEGURO.POLICYDCO P on TEMP.OPERACION = P.OPERATIONPK
LEFT JOIN INTERSEGURO.AGREGATEDPOLICY AP ON AP.AGREGATEDPOLICYID = P.AGREGATEDOBJECTID
INNER JOIN INTERSEGURO.PRODUCT PRO ON AP.PRODUCTID = PRO.PRODUCTID
LEFT JOIN INTERSEGURO.EVENTDCO E on P.IDDCOEVENT = E.IDDCOEVENT
INNER JOIN INTERSEGURO.EVENTTYPE E2 ON E2.EVENTTYPEID = E.EVENTTYPEID
WHERE E2.DESCRIPTION NOT IN ('CotizarVida','ReactivarCot','RechazarCot','Anular','Caducar')

SELECT COUNT(TIME_STAMP),TIME_STAMP FROM OPER_NOCOVERAGE TEMP
GROUP BY TEMP.TIME_STAMP;

SELECT * FROM OPER_NOCOVERAGE TEMP
WHERE TEMP.POLIZA = '500038-00919404'

SELECT * FROM INTERSEGURO.INTERMEDIO_DESGRAVAMEN
WHERE NUMERO_CERTIFICADO='00919404' AND NUMERO_POLIZA='500038'

SELECT * FROM INTERSEGURO.ASL_POLICYLOGICAL
142458348

SELECT * FROM INTERSEGURO.AGREGATEDPOLICY;
SELECT * FROM INTERSEGURO.CONTEXTOPERATION;
SELECT * FROM INTERSEGURO.POLICYDCO;
SELECT * FROM INTERSEGURO.STATE WHERE STATEID=81698;
SELECT * FROM INTERSEGURO.INTERMEDIO_DESGRAVAMEN;


SELECT NVL(SUBSTR('500038-00919404', 0, INSTR('500038-00919404', '-')-1), '500038-00919404') AS PARTE1,
NVL(SUBSTR('500038-00919404', INSTR('500038-00919404', '-'),LENGTH('500038-00919404'), '500038-00919404')) AS PARTE2
  FROM DUAL