select * from interseguro.tercero;

select * from interseguro.personanatural
where fechanacimientoinput = '1933-04-14';

select * from interseguro.prepolicy;

SELECT * FROM INTERSEGURO.INTERMEDIO_DESGRAVAMEN
WHERE NUMERO_DOCUMENTO='07818407'

SELECT * FROM INTERSEGURO.STPO_POLICYASLOGICAL
WHERE PAL_PK=128345181 


SELECT * FROM INTERSEGURO.STPO_POLICYASLPHYSICAL
WHERE PAL_PK=3623632 

SELECT * FROM INTERSEGURO.PRODUCT;


  SELECT DISTINCT TABLE_NAME,COLUMN_NAME
    FROM ALL_TAB_COLS
   WHERE COLUMN_NAME LIKE '%EDAD%'

SELECT EDADMAXIMAINPUT FROM INTERSEGURO.DESGTARJETAS;
EDADLIMITEINGRESOINPUT

SELECT * FROM INTERSEGURO.PREPOLICY
WHERE FECHAEVENTOANTERIORINPUT IS NULL

SELECT * FROM INTERSEGURO.POLIZA
WHERE NUMEROPOLIZA='500031-421274'

SELECT * FROM INTERSEGURO.POLICYDCO 
WHERE DCOID=1759337403

SELECT * FROM INTERSEGURO.CONTEXTOPERATION
WHERE ID = 177334947;

SELECT DISTINCT PRE.NUMEROPOLIZAINPUT AS POLIZA,(SELECT EDADMAXIMAINPUT FROM INTERSEGURO.DESGTARJETAS) AS EDADMAX,
trunc((trunc(to_date(PRE.FECHAEMISIONINPUT,'YYYY/MM/DD'))-trunc(to_date(FNACTRAMAINPUT,'YYYY/MM/DD')))/365) as EDAD,
PDT.NUMERODOCTRAMAINPUT,PDT.FNACTRAMAINPUT,PRE.FECHAEMISIONINPUT,PDT.NOMBREUNOTRAMAINPUT,PDT.NOMBREDOSTRAMAINPUT,PDT.APELLIDOUNOTRAMAINPUT,PDT.APELLIDODOSTRAMAINPUT
FROM INTERSEGURO.PREPOLICY PRE

--INNER JOIN INTERSEGURO.POLICYDCO PDCO ON PDCO.DCOID=PRE.PK
--INNER JOIN INTERSEGURO.AGREGATEDPOLICY AG ON AG.AGREGATEDPOLICYID = PDCO.AGREGATEDOBJECTID
INNER JOIN INTERSEGURO.POLDESGTARJETAS PDT ON PRE.STATIC = PDT.STATIC
WHERE PRE.FECHAEVENTOANTERIORINPUT IS NULL AND trunc((trunc(to_date(PRE.FECHAEMISIONINPUT,'YYYY/MM/DD'))-trunc(to_date(FNACTRAMAINPUT,'YYYY/MM/DD')))/365)>72--(SELECT EDADMAXIMAINPUT FROM INTERSEGURO.DESGTARJETAS)
 --AND PDT.STATIC = 87520286

SELECT * FROM INTERSEGURO.POLDESGTARJETAS


 
PDT.FNACTRAMAINPUT
WHERE STATIC = 87520286

FROM INTERSEGURO.POLICYDCO PDCO

select NUMERODOCTRAMAINPUT,FNACTRAMINPUT,PRE.FECHAEMISIONINPUT,NOMBREUNOTRAMAINPUT,NOMBREDOSTRAMAINPUT,APELLIDOUNOTRAMAINPUT,APELLIDODOSTRAMAINPUT
from interseguro.POLDESGTARJETAS
WHERE STATIC = 87520286


select *
from interseguro.POLDESGTARJETAS
WHERE STATIC = 87520286


SELECT * FROM INTERSEGURO.PRODUCT



        
