SELECT * FROM PREPOLICY WHERE NUMEROPOLIZAINPUT LIKE '500105-4552188%'

SELECT * FROM PRODUCT WHERE DESCRIPTION = 'DesgTarjetasIndividual';

SELECT COUNT(1) FROM AGREGATEDPOLICY WHERE PRODUCTID = 73585;