DECLARE
ISCORRECT VARCHAR2(10);
BEGIN
    SELECT CASE BIMONEDAINPUT WHEN 'Si' THEN 'OK'
    ELSE 'ERROR' END INTO ISCORRECT  FROM INTERSEGURO.PREPRODUCT WHERE CODIGOPRODUCTOASINPUT = 'DESGRAVAMEN TARJETAS INDIVIDUAL';
    DBMS_OUTPUT.PUT_LINE('PREPRODUCT INPUT = ' || ISCORRECT);
    ISCORRECT := null;
    SELECT CASE BIMONEDAVALUE WHEN '1.0' THEN 'OK'
    ELSE 'ERROR' END INTO ISCORRECT  FROM INTERSEGURO.PREPRODUCT WHERE CODIGOPRODUCTOASINPUT = 'DESGRAVAMEN TARJETAS INDIVIDUAL';
    DBMS_OUTPUT.PUT_LINE('PREPRODUCT VALUE = ' || ISCORRECT);
    ISCORRECT := null;
    SELECT CASE SYP_VALUE WHEN 'Y' THEN 'OK' ELSE 'ERROR' END INTO ISCORRECT FROM INTERSEGURO.STST_SYSTEMPROPERTY  WHERE SYP_PROPERTY = 'enableDualCurrencySearch';
    DBMS_OUTPUT.PUT_LINE('STST_SYSTEMPROPERTY = ' || ISCORRECT);
    ISCORRECT := null;
    SELECT CASE COUNT(1) WHEN 1 THEN 'OK' ELSE 'ERROR' END INTO ISCORRECT FROM ALL_TAB_COLUMNS WHERE OWNER = 'INTERSEGURO' AND TABLE_NAME = 'INT_DESG_PROCESS' AND COLUMN_NAME = 'SALDO_PROMEDIO';
    DBMS_OUTPUT.PUT_LINE('INT_DESG_PROCESS = ' || ISCORRECT);
    ISCORRECT := null;
    SELECT CASE COUNT(1) WHEN 1 THEN 'OK' ELSE 'ERROR' END INTO ISCORRECT FROM INTERSEGURO.STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK';
    DBMS_OUTPUT.PUT_LINE('STPS_AGREEMENTSTATICDAT = ' || ISCORRECT); 
    ISCORRECT := null;
    SELECT CASE COUNT(1) WHEN 1 THEN 'OK' ELSE 'ERROR' END INTO ISCORRECT FROM  INTERSEGURO.STAG_AGREEMENTVERSION WHERE DESCRIPTION = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK - Soles/Dolares';
    DBMS_OUTPUT.PUT_LINE('STAG_AGREEMENTVERSION = ' || ISCORRECT); 
    ISCORRECT := null;
    SELECT CASE MONEDAACUERDOINPUT WHEN 'Nuevo Sol,US Dolar' THEN 'OK' ELSE 'ERROR' END INTO ISCORRECT FROM INTERSEGURO.POLMATRIZPB WHERE PK IN (SELECT dcoid FROM STAG_AGREEMENTVERSION WHERE AST_ID =
    (SELECT AST_ID FROM STPS_AGREEMENTSTATICDAT WHERE AST_NOMBREACU = 'Poliza Maestra Desgravamen Tarjeta Credito Individual IBK'));
    DBMS_OUTPUT.PUT_LINE('POLMATRIZPB = ' || ISCORRECT); 
    ISCORRECT := null;
    SELECT CASE INT_DESG_JOB.GET_LASTPART_NUMPOL('DesgTarjetasIndividual','01') WHEN '-1' THEN 'OK'
    ELSE 'ERROR' END INTO ISCORRECT FROM DUAL;
    DBMS_OUTPUT.PUT_LINE('INT_DESG_JOB = ' || ISCORRECT); 
    ISCORRECT := null;
    SELECT CASE COUNT(1) WHEN 1 THEN 'OK' ELSE 'ERROR' END INTO ISCORRECT FROM ALL_TAB_COLUMNS WHERE OWNER = 'INTERSEGURO' AND TABLE_NAME = 'INTERMEDIO_DESGRAVAMEN' AND COLUMN_NAME = 'SALDO_PROMEDIO';
    DBMS_OUTPUT.PUT_LINE('INTERMEDIO_DESGRAVAMEN.SALDO_PROMEDIO = ' || ISCORRECT); 
    ISCORRECT := null;
    SELECT CASE COUNT(1) WHEN 1 THEN 'OK' ELSE 'ERROR' END INTO ISCORRECT FROM ALL_TAB_COLUMNS WHERE OWNER = 'INTERSEGURO' AND TABLE_NAME = 'INTERMEDIO_DESGRAVAMEN' AND COLUMN_NAME = 'MONCOM';
    DBMS_OUTPUT.PUT_LINE('INTERMEDIO_DESGRAVAMEN.MONCOM = ' || ISCORRECT); 
    /*ISCORRECT := null;
    SELECT COUNT(DISTINCT PRE.NUMEROPOLIZAINPUT) INTO ISCORRECT
			FROM INTERSEGURO.AGREGATEDPOLICY AG
	JOIN INTERSEGURO.PRODUCT PRO ON AG.PRODUCTID = PRO.PRODUCTID
	JOIN INTERSEGURO.PREPOLICY PRE ON PRE.STATIC = AG.AGREGATEDPOLICYID
	WHERE PRO.DESCRIPTION IN ('DesgTarjetasIndividual');
	DBMS_OUTPUT.PUT_LINE('TOTAL POLIZAS = ' || ISCORRECT); 
    ISCORRECT := null;
    SELECT COUNT(1) INTO ISCORRECT FROM INTERSEGURO.BIMONEDACONTROL;
     DBMS_OUTPUT.PUT_LINE('TOTAL PROCESADAS = ' || ISCORRECT); 
    ISCORRECT := null;*/
END;




