INSERT INTO APP_VIDA.STST_SYSTEMPROPERTY (SYP_PROPERTY, SYP_VALUE, SYP_TYPE, SYP_MODULE, SYP_ISNULLABLE) VALUES ('stockDueDate', '2022-08-10', 7, 'PO', 1);
INSERT INTO APP_VIDA.STST_SYSTEMPROPERTY (SYP_PROPERTY, SYP_VALUE, SYP_TYPE, SYP_MODULE, SYP_ISNULLABLE) VALUES ('dynamicEvents', 'GenerarPrima', 7, 'PO', 1);
INSERT INTO APP_VIDA.STST_SYSTEMPROPERTY (SYP_PROPERTY, SYP_VALUE, SYP_TYPE, SYP_MODULE, SYP_ISNULLABLE) VALUES ('stockEvents', 'Consumo', 7, 'PO', 1);

INSERT INTO APP_VIDA.RIMAC_EQUIVALENCIES (ID, PROPERTY, SASVALUE, EQUIVALENCE) VALUES (SQ_RIMAC_EQUIVALENCIES.nextval, 'DesgSubPlanEq','149','PlanConsumerFinanceB');
INSERT INTO APP_VIDA.RIMAC_EQUIVALENCIES (ID, PROPERTY, SASVALUE, EQUIVALENCE) VALUES (SQ_RIMAC_EQUIVALENCIES.nextval, 'DesgSubPlanEq','150','PlanConsumerFinanceD');
INSERT INTO APP_VIDA.RIMAC_EQUIVALENCIES (ID, PROPERTY, SASVALUE, EQUIVALENCE) VALUES (SQ_RIMAC_EQUIVALENCIES.nextval, 'DesgSubPlanEq','151','PlanConsumerFinanceO');
