DECLARE
  V_CLAIMID NUMBER;
  V_CLAIMNUMBER VARCHAR2(100) := 'VTC1-2023-42';
  V_CNR_ID NUMBER;
BEGIN
	FOR CL IN( SELECT CLAIMID  FROM CLAIM WHERE CLAIMNUMBER =  V_CLAIMNUMBER) LOOP
	V_CLAIMID := CL.CLAIMID;
	FOR I IN (SELECT I.CLAIMNORMALRESERVEDID FROM CLAIMNORMALRESERVE WHERE CLAIMINSURANCEOBJECTID IN
	(SELECT CLAIMINSURANCEOBJECTID FROM CLAIMINSURANCEOBJECT WHERE CLAIMRISKUNITID IN
										(SELECT CLAIMRISKUNITID FROM CLAIMRISKUNIT WHERE CLAIMID= V_CLAIMID))) LOOP
		V_CNR_ID := I.CLAIMNORMALRESERVEDID;

		FOR DCL IN (SELECT OPM_ID FROM STRI_OPHISTDETAILCLAIM WHERE CNR_ID = V_CNR_ID) LOOP
			DELETE FROM STRI_OPHISTDETAILCLAIM WHERE OPM_ID = DCL.OPM_ID;
			DELETE FROM OPENITEM WHERE OPENITEMID =  DCL.OPM_ID;
		END LOOP;

		DELETE FROM STRI_OPHISTDETAILCLAIM WHERE CNR_ID = V_CNR_ID;
		DELETE FROM STCL_RESERVESTATE WHERE CNR_ID = V_CNR_ID;
		DELETE FROM CLAIMREQUISITE WHERE CNR_ID = V_CNR_ID;

		FOR I IN (SELECT CLAIMPAYMENTID, CLAIMID  FROM CLAIMPAYMENT WHERE CLAIMPAYMENTID IN (SELECT CPY_ID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID)) LOOP
			DELETE FROM STCL_CLAIMPAYMENTRISKUNIT WHERE CLAIMPAYMENTID = I.CLAIMPAYMENTID;
			DELETE FROM ENTRY WHERE PK IN (SELECT ECP_ENTRYID FROM STEN_ENTRYCLAIMPAYMENT WHERE CPY_ID IN (SELECT CLAIMPAYMENTID FROM CLAIMPAYMENT WHERE CLAIMPAYMENTID = I.CLAIMPAYMENTID));
			DELETE FROM STEN_ENTRYCLAIMPAYMENT WHERE CPY_ID IN (SELECT CLAIMPAYMENTID FROM CLAIMPAYMENT WHERE CLAIMID =I.CLAIMID);
		END LOOP;

		DELETE FROM STAD_CLAIMCONTEXT WHERE POD_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE CRBF_ID IN
																		  (SELECT CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID));
		DELETE FROM STCL_PAYMENTSTATE WHERE POR_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE CRBF_ID IN
																		  (SELECT CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID));
		DELETE FROM RI_CLAIMOPERATIONS WHERE POR_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE CRBF_ID IN
																				  (SELECT CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID));
		DELETE FROM STCA_CLAIMBENEFICIARY WHERE CRBF_ID IN (SELECT CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID);
		DELETE FROM STHC_ENDORSEMENTLETTER WHERE CNR_ID = V_CNR_ID;
		DELETE FROM STCL_COVERAGEINVOICEDETAIL CD WHERE CD.COVI_INVOICE IN (SELECT COVI_INVOICE FROM STCL_COVERAGEINVOICE WHERE CRBF_ID IN
																								  (SELECT CRB.CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID));
		DELETE FROM STCL_COVERAGEINVOICE WHERE CRBF_ID IN (SELECT CRB.CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID);
		DELETE FROM STCA_CLAIMBENEFICIARY CRBB WHERE CRBB.CRBF_ID IN (SELECT CRB.CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID);
		DELETE FROM STCL_PAYMENTSTATE WHERE POR_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID);
		DELETE FROM STAD_CLAIMCONTEXT WHERE POD_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID);
		FOR POR IN (SELECT OPM_ID FROM STCL_PAYMENTLIQUIDATION WHERE POR_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID)) LOOP
			DELETE FROM STCL_PAYMENTLIQUIDATION WHERE OPM_ID = POR.OPM_ID;
			DELETE EXT_INTERFPAYMENTMOVEMENT WHERE OPENITEMID = POR.OPM_ID;
			DELETE STCA_OPENITEMLIQINFO WHERE OPM_ID = POR.OPM_ID;
			DELETE FROM OPENITEM WHERE OPENITEMID = POR.OPM_ID;

		END LOOP;

		DELETE FROM PAYMENTORDER WHERE CRBF_ID IN (SELECT CRBF_ID FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID);
		DELETE FROM STCL_CLAIMRESERVEBENEFIT CRB WHERE CRB.CNR_ID = V_CNR_ID;
		DELETE FROM RI_CLAIMOPERATIONDETAILS WHERE CLAIMOPERATIONID IN
												 (SELECT CLAIMOPERATIONID FROM RI_CLAIMOPERATIONS WHERE POR_ID IN 
																			  (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID));

		DELETE RI_CLAIMOPERATIONS WHERE POR_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID);
		DELETE FROM PAYMENTORDERDETAIL WHERE  PAYMENTORDERID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID);
		DELETE FROM STCL_PAYMENTACCOUNT WHERE POR_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID);
		DELETE FROM PAYMENTORDER WHERE FKRESERVE = V_CNR_ID;

		DELETE FROM RI_CLAIMOPERATIONDETAILS WHERE CLAIMOPERATIONID IN
												 (SELECT CLAIMOPERATIONID FROM RI_CLAIMOPERATIONS WHERE CRA_ID IN 
																			  (SELECT CLAIMRESERVEADJUSTID  FROM CLAIMRESERVEADJUST WHERE CLAIMRESERVEID = V_CNR_ID));

		DELETE RI_CLAIMOPERATIONS WHERE CRA_ID IN (SELECT CLAIMRESERVEADJUSTID  FROM CLAIMRESERVEADJUST WHERE CLAIMRESERVEID = V_CNR_ID);
		DELETE FROM STAD_CLAIMCONTEXT WHERE CLA_ID IN (SELECT CLAIMID  FROM CLAIM WHERE CLAIMNUMBER = V_CLAIMNUMBER);
		DELETE FROM CLAIMRESERVEADJUST WHERE CLAIMRESERVEID = V_CNR_ID;
		DELETE FROM CLAIMNORMALRESERVE WHERE CLAIMNORMALRESERVEDID = V_CNR_ID;

	END LOOP;

	DELETE FROM STCL_PAYMENTACCOUNT WHERE POR_ID IN (SELECT PAYMENTORDERID FROM PAYMENTORDER WHERE CPY_ID IN (SELECT CLAIMPAYMENTID  FROM CLAIMPAYMENT WHERE CLAIMID =  V_CLAIMID));
	DELETE CLAIMRESERVEBYCONCEPT WHERE CLAIMINSURANCEOBJECTID IN (SELECT CLAIMINSURANCEOBJECTID FROM CLAIMINSURANCEOBJECT WHERE CLAIMRISKUNITID IN
																								(SELECT CLAIMRISKUNITID FROM CLAIMRISKUNIT WHERE CLAIMID= V_CLAIMID));
	DELETE FROM CLAIMINSURANCEOBJECT WHERE CLAIMRISKUNITID IN (SELECT CLAIMRISKUNITID FROM CLAIMRISKUNIT WHERE CLAIMID= V_CLAIMID);
	DELETE FROM STCL_CLAIMPAYMENTRISKUNIT WHERE CLAIMRISKUNITID IN (SELECT CLAIMRISKUNITID FROM CLAIMRISKUNIT WHERE CLAIMID= V_CLAIMID);
	DELETE FROM CLAIMRISKUNIT WHERE CLAIMID= V_CLAIMID;
	DELETE FROM STAD_CLAIMCONTEXT WHERE CLA_ID = V_CLAIMID;
	DELETE FROM STCL_CLAIMOPERATIONHISTORY WHERE CLAIMID =V_CLAIMID;
	DELETE FROM STRP_CLAIMLETTERHISTORY WHERE CLAIMID =V_CLAIMID;
	DELETE FROM STCL_STATE WHERE CLA_ID =V_CLAIMID;
	DELETE FROM PAYMENTORDER WHERE CPY_ID IN (SELECT CLAIMPAYMENTID  FROM CLAIMPAYMENT WHERE CLAIMID =  V_CLAIMID);
	DELETE FROM CLAIMPAYMENT WHERE CLAIMID =V_CLAIMID;
	DELETE FROM CLAIM WHERE CLAIMID =V_CLAIMID;

	--COMMIT;
	END LOOP;
END;