CREATE SEQUENCE SQ_EXT_FAILEDOPERATION
  START WITH 1 INCREMENT BY 202 MAXVALUE 999999999999999999999999999
  MINVALUE 0 NOCYCLE CACHE 500 ORDER;

ALTER TABLE INTERSEGURO.EXT_FAILEDOPERATION DROP PRIMARY KEY;

ALTER TABLE INTERSEGURO.EXT_FAILEDOPERATION ADD FLD_ID NUMBER(19);

UPDATE INTERSEGURO.EXT_FAILEDOPERATION
  SET FLD_ID = SQ_HELP.GET_SQ('SQ_EXT_FAILEDOPERATION')
WHERE FLD_ID IS NULL;

COMMIT;

ALTER TABLE INTERSEGURO.EXT_FAILEDOPERATION ADD CONSTRAINT FLD_PK PRIMARY KEY (FLD_ID);

COMMIT;