DECLARE
  V_QUERYSELECT  VARCHAR2(10000);
BEGIN
  FOR K IN (
  SELECT A.CONSTRAINT_NAME,
    A.TABLE_NAME AS REF_TABLE,
    A.COLUMN_NAME AS REF_COLUMN,
    C_PK.TABLE_NAME TABLE_NAME,
    B.COLUMN_NAME
  FROM USER_CONS_COLUMNS A
    JOIN USER_CONSTRAINTS C ON A.OWNER = C.OWNER AND A.CONSTRAINT_NAME = C.CONSTRAINT_NAME
    JOIN USER_CONSTRAINTS C_PK ON C.R_OWNER = C_PK.OWNER AND C.R_CONSTRAINT_NAME = C_PK.CONSTRAINT_NAME
    JOIN USER_CONS_COLUMNS B ON C_PK.OWNER = B.OWNER AND  C_PK.CONSTRAINT_NAME = B.CONSTRAINT_NAME AND B.POSITION = A.POSITION
  WHERE B.COLUMN_NAME='OPENITEMID'
  )
  LOOP
    BEGIN
      V_QUERYSELECT:='SELECT * FROM ' || K.REF_TABLE || ' WHERE '|| K.REF_COLUMN || ' IN (select openitemid from openitem where operationpk in (181808102
188685072
191632444
191635045);';
      dbms_output.put_line(V_QUERYSELECT);
    END;
  END LOOP;
END;