select OI.*
from INTERSEGURO.CONTEXTOPERATION COT 
inner join INTERSEGURO.AGREGATEDPOLICY AP on COT.ITEM = AP.AGREGATEDPOLICYID
inner join INTERSEGURO.PRODUCT P on AP.PRODUCTID = P.PRODUCTID
inner join INTERSEGURO.POLICYDCO PDCO on PDCO.OPERATIONPK = COT.id
inner join INTERSEGURO.PREPOLICY PP on PP.PK = PDCO.DCOID
inner join INTERSEGURO.OPENITEM OI on OI.OPERATIONPK = COT.id
where pp.numeropolizainput IN ('1160103-00541017','1160103-00540925','1160103-00536942')
--group by oi.openitemid,oi.docdate,oi.openitemdate